# Data Preparation for the Beer Model

In [2]:


from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive

There are two data sets on data about beer sold in stores
namely "out_of_stock" and "sales data". These datasets need to be cleaned and merged.

In [3]:
import pandas as pd
out_of_stock = pd.read_csv('/content/gdrive/MyDrive/Beer/out_of_stock_data.csv')

In [4]:
display(out_of_stock.head())

,YEAR_MONTH_WK,DivisionNum,StoreNum,UPC,UPC_Description,DATE_KEY,DSD_Vendor_Name
0,2019 PD 03 WK 2 (10),26.0,520.0,8.179040e+10,ELYSIAN SPACE DUST 6P BTL,2019-04-11,026 AJAX TURNER CO INC
1,2019 PD 12 WK 1 (45),26.0,862.0,7.800001e+09,DIET 7UP CHERRY,2019-12-10,026 AMERICAN BTLG CO
2,2019 PD 02 WK 4 (08),620.0,410.0,1.200017e+09,BUBLY SPRKLG WRT MNGO 8PK,2019-03-28,620 PEPSI COLA WEST
3,2019 PD 12 WK 1 (45),24.0,776.0,2.840019e+09,TSTO LGHTY SLTD TORTILLA,2019-12-08,024 FRITO LAY INC
4,2019 PD 05 WK 3 (19),660.0,134.0,8.581760e+10,BDYARMR PNAPPLE CCNT DRNK,2019-06-10,660 KALIL BTLG CO

# Sales Data and Out_of_Stock

In [5]:
sales_data = pd.read_csv('/content/gdrive/MyDrive/Beer/sales_data_weekly.csv')
sales_data.head()

,YEAR_MONTH_WK,UPC,RPT_SHORT_DESC,RE_STO_NUM,SCANNED_RETAIL_DOLLARS,SCANNED_MOVEMENT,SCANNED_LBS,GROSS_MARGIN_DOLLARS
0,2018 PD 08 WK 4 (32),85562300215,705 QFC,850,99.90,10.0,0.0,0.0
1,2018 PD 01 WK 1 (01),1820053047,705 QFC,803,135.87,13.0,0.0,19.0
2,2018 PD 08 WK 4 (32),70277006301,705 QFC,126,9.99,1.0,0.0,0.0
3,2020 PD 03 WK 3 (11),8378337521,706 Smiths,376,18.96,2.0,0.0,0.0
4,2018 PD 01 WK 1 (01),3410000323,706 Smiths,355,17.50,7.0,0.0,0.0

In [6]:
out_of_stock.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5296921 entries, 0 to 5296920
Data columns (total 7 columns):
 #   Column           Dtype
---  ------           -----
 0   YEAR_MONTH_WK    object
 1   DivisionNum      float64
 2   StoreNum         float64
 3   UPC              float64
 4   UPC_Description  object
 5   DATE_KEY         object
 6   DSD_Vendor_Name  object
dtypes: float64(3), object(4)
memory usage: 282.9+ MB

In [7]:
out_of_stock.describe()

        DivisionNum      StoreNum           UPC
count  5.296920e+06  5.296920e+06  5.296920e+06
mean   1.983804e+02  5.202579e+02  2.059414e+10
std    2.825885e+02  3.084824e+02  3.251050e+10
min    1.100000e+01  1.000000e+00  2.080000e+02
25%    2.100000e+01  2.120000e+02  2.840021e+09
50%    2.400000e+01  5.670000e+02  7.131400e+09
75%    6.200000e+02  7.640000e+02  8.600325e+09
max    7.050000e+02  9.980000e+02  9.310072e+11

In [8]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8064442 entries, 0 to 8064441
Data columns (total 8 columns):
 #   Column                  Dtype
---  ------                  -----
 0   YEAR_MONTH_WK           object
 1   UPC                     int64
 2   RPT_SHORT_DESC          object
 3   RE_STO_NUM              int64
 4   SCANNED_RETAIL_DOLLARS  float64
 5   SCANNED_MOVEMENT        float64
 6   SCANNED_LBS             float64
 7   GROSS_MARGIN_DOLLARS    float64
dtypes: float64(4), int64(2), object(2)
memory usage: 492.2+ MB

In [9]:
sales_data.describe()

,UPC,RE_STO_NUM,SCANNED_RETAIL_DOLLARS,SCANNED_MOVEMENT,SCANNED_LBS,GROSS_MARGIN_DOLLARS
count,8.064442e+06,8.064442e+06,8.064442e+06,8.064442e+06,8.064442e+06,8.064442e+06
mean,3.068995e+10,4.548358e+02,6.258238e+01,6.630301e+00,9.362086e-07,1.958884e+00
std,3.606966e+10,2.897584e+02,1.205303e+02,1.121233e+01,1.812539e-03,1.478191e+01
min,9.000000e+00,1.000000e+00,-5.050000e+02,-1.300000e+01,0.000000e+00,-3.650560e+03
25%,3.410000e+09,1.900000e+02,1.798000e+01,2.000000e+00,0.000000e+00,0.000000e+00
50%,8.066096e+09,3.780000e+02,3.468000e+01,4.000000e+00,0.000000e+00,0.000000e+00
75%,7.221602e+10,8.210000e+02,6.643000e+01,7.000000e+00,0.000000e+00,0.000000e+00
max,8.809289e+11,8.940000e+02,1.289197e+04,1.403000e+03,4.720000e+00,7.946400e+02

In [10]:
# Column Titles are converted to lower-case
s  = out_of_stock.columns
out_of_stock.columns = s.str.lower()

s  = sales_data.columns
sales_data.columns = s.str.lower()

In [14]:
# Counting the number of non-NaN entries in the two datasets; out_of_stock and sales_data

(out_of_stock.count(), sales_data.count())

(year_month_wk      5296920
 divisionnum        5296920
 storenum           5296920
 upc                5296920
 upc_description    5296920
 date_key           5296920
 dsd_vendor_name    5296920
 dtype: int64,
 year_month_wk             8064442
 upc                       8064442
 rpt_short_desc            8064442
 re_sto_num                8064442
 scanned_retail_dollars    8064442
 scanned_movement          8064442
 scanned_lbs               8064442
 gross_margin_dollars      8064442
 dtype: int64)

In [15]:
#Count the number of 'NA's  in each dataset --- one way is to determine the shape of the two datasets and compare with
# the column counts of non-NaN values

(out_of_stock.shape[0], sales_data.shape[0])

#out_of_stock.isna() has 1 row of NA's
#sales_data no 'NA's

(5296921, 8064442)

In [16]:
# Removal of NaNs
# In general not entirely advisable; we do this only in the case of a 'few' rows containing 'NA's

out_of_stock.dropna(how = 'any', inplace = True)
sales_data.dropna(how = 'any', inplace = True)


out_of_stock.shape[0], sales_data.shape[0]

(5296920, 8064442)

In [17]:
# Duplicates
# There are no duplicates in the out_of_stock and sales datasets

sum(out_of_stock.duplicated()),sum(sales_data.duplicated())

(0, 0)

In [18]:
# replacing the divisionnum as a string
# that is, three digit codes
out_of_stock['division_code'] = out_of_stock['divisionnum'].astype('int')
out_of_stock['division_code'] = out_of_stock['division_code'].astype('str')

out_of_stock['division_code'] = ['0' + x if len(x) == 2 else x for x in out_of_stock['division_code'].tolist()] # padding strings of 2 digits with '0'.

sales_data['division_code'] = sales_data['rpt_short_desc'].str.slice(start = 0, stop = 3)

sales_data['manager_on_floor'] = sales_data['rpt_short_desc'].str.slice(start = 3)

In [19]:
# Setting the store names as string-type
out_of_stock['storenum'] = out_of_stock['storenum'].astype('int')
out_of_stock['storenum'] = out_of_stock['storenum'].astype('str')

sales_data['storenum'] = sales_data['re_sto_num'].astype('str')

In [20]:
# Creating "new_year_mth_wk' column

out_of_stock['new_year_mth_wk'] = out_of_stock['year_month_wk'].str.slice(start = 0, stop = 17)
sales_data['new_year_mth_wk'] = sales_data['year_month_wk'].str.slice(start = 0, stop = 17)

In [21]:
# Change dtype of 'upc' to integer

out_of_stock['upc'] = out_of_stock['upc'].astype('int')

# Comment: We only use intersecting division_codes and storenums in the out_of_stock and sales_data

In [22]:

sales_data['division_code'].unique()

array(['705', '706'], dtype=object)

In [23]:

out_of_stock['division_code'].unique()

array(['026', '620', '024', '660', '021', '701', '705', '011'],
      dtype=object)

In [24]:

# We only use overlapping divisionnums and storenums in the out_stock and sales_dat
 # Division =  '705' is the only divisionnum in both 'sales' and 'out_stock'


a = list(sales_data['division_code'] == '705')
sales_data = sales_data[a]

b = list(out_of_stock['division_code'] == '705')
out_of_stock = out_of_stock[b]

In [25]:
# Removal of upc values from the sales_ab dataset that do not ever appear in the out_of_stock data.
''' Justification for removing the upc values that do not ever appear in the out_stock_data:
      Over the time period considered, these codes have never appeared in out_of_stock data so from
      a modelling perspective there is no indication they have ever been 'out_of_stock' hence they will
      be assigned a very low (or zero) probability of being recorded as out of stock.
      For this reason upcs that do not appear in the out_of_stock file are removed.
'''
A = set(sales_data['upc'])
B = set(out_of_stock['upc'])
a = list(B.intersection(A)) # upc codes common to both A and B
print(len(a))
# Note we choose upc codes that  occur in the sales data set( otherwise we have an absence of sales data for some upc codes)

s = list(sales_data['upc'])
s_bool = [x in a  for x in s ]

sales_data = sales_data[s_bool]   # keeping upc codes common to both out_of_stock and sales_data

754

In [26]:
'''
1)
    a) Note the variable 'scanned_lbs' is entirely 0 and can be deleted from the sales_ab data



    b) Cases where the upc description takes on different forms

                upc        upc_description
24990    1820097009    BUD LIGHT CALNR 12CT
46308    1820097009    BUD LIGHT  CALNR 12CT
2570445  1820097009    BUD LIGHTCALNR 12CT




2) Rationale for left join:
   'storenums' that do not ever appear in the sales data (but in the out_stock data) will not have any recorded sales information -- from a
   modelling perspective this is a lack of information which results in greater uncertainty in predictions for these stores (the financial data will have NaNs)
   To avoid this situation, we settle for a left join, i.e., all the required elements from the sales_data are kept and 'storenums' that do not have sales data are dropped
'''

new_merge = sales_data[['upc', 'storenum',
       'scanned_retail_dollars', 'scanned_movement',
       'gross_margin_dollars', 'division_code', 'manager_on_floor',
       'new_year_mth_wk']].merge(out_of_stock[['upc', 'upc_description', 'date_key', 'storenum', 'new_year_mth_wk', 'dsd_vendor_name']]
                                 , how = 'left', suffixes = ('_x', None)
                                 , on = ['new_year_mth_wk', 'upc',  'storenum']

                                )

In [27]:
new_merge.describe()

,upc,scanned_retail_dollars,scanned_movement,gross_margin_dollars
count,2.477237e+06,2.477237e+06,2.477237e+06,2.477237e+06
mean,4.192492e+10,4.995006e+01,5.085329e+00,2.047229e+00
std,3.724037e+10,6.583133e+01,6.253484e+00,6.247075e+00
min,9.125003e+08,-9.098000e+01,-1.300000e+01,-6.597150e+02
25%,7.199010e+09,1.899000e+01,2.000000e+00,0.000000e+00
50%,9.530113e+09,3.297000e+01,3.000000e+00,0.000000e+00
75%,8.179040e+10,5.994000e+01,6.000000e+00,0.000000e+00
max,8.994430e+10,4.539650e+03,2.550000e+02,7.946400e+02

In [28]:
# All storenums in new_merge are now contained in out_stock data (see the snippet below)
A = set(new_merge['storenum'])
B = set(out_of_stock['storenum'])

A.issubset(B)

True

In [29]:
########################################## Checking the variables in new_merge
# The 'date_key' is only populated with a date entry when there is a detected out of stock shelf.
a = new_merge['date_key'].isna()

b = [not(x) for x in a]  #entries for which there is an out_of_stock shelf detected


# 1   checking the month / year of the date_key
p = new_merge['date_key'][b].str.slice(start = 5, stop = 7)
# sanity check
sum(p.astype(int) > 12) # should be 0
sum(p.astype(int) < 1)  # should be 0


p = new_merge['date_key'][b].str.slice(start = 0, stop = 4)

d = sum(p.astype(int) == 2020)  # get 0 entries here
e= sum(p.astype(int) == 2019)
f = sum(p.astype(int) == 2018)
(d, e, f)

(0, 4377, 12278)

In [30]:
# Constructing a (0,1)-response variable from the date_key


a = new_merge['date_key'].isna() # Recall that the 'date_key' variable is populated with a date entry
                                 # only when an out of stock shelf is detected during a daily check.
b = [int(not(x)) for x in a]

new_merge["target_out_stock"] = b # this includes labelling several days within a week as out of stock( i.e. if those days are 'out_of_stock' for a particular product)

round(sum(new_merge['target_out_stock'])/new_merge.shape[0], 3) # proportion of days out of stock with respect to historical data :

0.007

In [31]:
# We look at when there was a last detection of out_of_stock for this data.
d = new_merge['date_key'].sort_values()

f = [not(x) for x in list(d.isna())]
d[f] # last date 2019/11/30
pos = d[f].shape[0]


list(d[f])[pos-1]

'2019-11-30'

In [32]:
# The 'UPC' codes: We need to ensure that UPC codes are the same for both 'out_of_stock' and 'sales_data '

# Since the UPC digits are codes, the UPCs have to be strings in a model.
new_merge['upc'] = new_merge['upc'].astype('str')  # upc values are strings


# There are UPC codes in new_merge with NaNs in the upc_description; however these UPC codes DO HAVE a description - we set these descriptions
print(new_merge['upc_description'].isna().sum())


tst =  out_of_stock[['upc', 'upc_description']].drop_duplicates('upc')  # drop duplicates wrt 'upc' numbers
tst['upc'] = tst['upc'].astype('str')  # upc values are strings

'''
Comment:
Here is a case where the upc numbers are different but the upc_descriptions are the same:

         upc            upc_description
47988  85016200819  10 BARREL APOCLYPS 6P CAN
51168  85016200806  10 BARREL APOCLYPS 6P CAN
'''

# Hence we calc
tst2 = tst.drop_duplicates('upc_description')


new_m2 =  new_merge.drop('upc_description', axis = 1).merge(tst2, on = ['upc'], how = 'inner', suffixes = ('_x', None) )

# Assign new_m2 as the current new_merge

new_merge = new_m2

del new_m2
print(new_merge.shape, "shape")
print(new_merge['upc_description'].isna().sum())

2460582
(2472037, 12) shape
0

In [33]:
 # save new_merge as a csv file

new_merge.to_csv("/content/gdrive/My Drive/Beer/new_merge.csv", index=False)

In [34]:
import pandas as pd
new_merge = pd.read_csv('/content/gdrive/MyDrive/Beer/new_merge.csv')
(new_merge.columns, new_merge.shape)

(Index(['upc', 'storenum', 'scanned_retail_dollars', 'scanned_movement',
        'gross_margin_dollars', 'division_code', 'manager_on_floor',
        'new_year_mth_wk', 'date_key', 'dsd_vendor_name', 'target_out_stock',
        'upc_description'],
       dtype='object'),
 (2472037, 12))

In [35]:
# Setting 'storenum' and 'upc' as string datatype
new_merge['storenum'].astype('str')
new_merge['upc'].astype('str')

0          85562300215
1           1820053047
2          78615000001
3           2210000760
4           4085002001
              ...
2472032     8769283231
2472033     8769283231
2472034     8769283231
2472035     8769283231
2472036     8769283231
Name: upc, Length: 2472037, dtype: object

In [36]:
new_merge.count()
# It appears here that we only have vendor names that have experienced 'out_of_stock' incidents

upc                       2472037
storenum                  2472037
scanned_retail_dollars    2472037
scanned_movement          2472037
gross_margin_dollars      2472037
division_code             2472037
manager_on_floor          2472037
new_year_mth_wk           2472037
date_key                    16629
dsd_vendor_name             16629
target_out_stock          2472037
upc_description           2472037
dtype: int64

In [37]:
# Creation of a modelling dataset


''' We need to aggregate over the 'upc', 'upc_description' , 'storenum' and 'new_year_mth_wk'  codes, 'manager_on_floor' and 'dsd_vendor_name'
in order to obtain the number of out_of_stocks per week

Note : That there is a 1-1 correspondence between 'upc' and 'upc_description', so it is redundant to include both
in a grouping function. We do so nevertheless - for later illustrations.
'''


x = ["target_out_stock", "gross_margin_dollars", "scanned_retail_dollars", 'scanned_movement']
df = new_merge.groupby(['upc', 'storenum', 'new_year_mth_wk', 'upc_description'])[x].sum()

new_merge_dat = df.reset_index()   # Here 'target_out_stock' represents the number of times per week a store and upc are out of stock.

In [38]:
new_merge_dat.shape

(2466275, 8)

In [39]:
new_merge_dat.head()

,upc,storenum,new_year_mth_wk,upc_description,target_out_stock,gross_margin_dollars,scanned_retail_dollars,scanned_movement
0,912500335,105,2018 PD 02 WK 4,ANDRS VLY HOLY GOSE 6P CN,0,0.0,8.58,2.0
1,912500335,106,2018 PD 01 WK 1,ANDRS VLY HOLY GOSE 6P CN,0,0.0,20.98,2.0
2,912500335,106,2018 PD 01 WK 4,ANDRS VLY HOLY GOSE 6P CN,0,0.0,8.24,1.0
3,912500335,106,2018 PD 02 WK 1,ANDRS VLY HOLY GOSE 6P CN,0,0.0,16.48,2.0
4,912500335,106,2018 PD 02 WK 2,ANDRS VLY HOLY GOSE 6P CN,0,0.0,18.72,3.0

In [40]:
#Constructing a 'Wks' and 'year' column from the 'new_year_mth_wk' variable
# Easier way: use str.slice for a pandas dataframe.
a = list(new_merge_dat['new_year_mth_wk'])
b  = [x.split() for x in a]
wks = [ ''.join([l[3], l[4]]) for l in b]
year = [l[0] for l in b]

new_merge_dat['wks'] = wks
new_merge_dat['year'] = new_merge_dat['new_year_mth_wk'].str.slice(start = 0, stop = 5)

In [41]:
new_merge_dat.head()

,upc,storenum,new_year_mth_wk,upc_description,target_out_stock,gross_margin_dollars,scanned_retail_dollars,scanned_movement,wks,year
0,912500335,105,2018 PD 02 WK 4,ANDRS VLY HOLY GOSE 6P CN,0,0.0,8.58,2.0,WK4,2018
1,912500335,106,2018 PD 01 WK 1,ANDRS VLY HOLY GOSE 6P CN,0,0.0,20.98,2.0,WK1,2018
2,912500335,106,2018 PD 01 WK 4,ANDRS VLY HOLY GOSE 6P CN,0,0.0,8.24,1.0,WK4,2018
3,912500335,106,2018 PD 02 WK 1,ANDRS VLY HOLY GOSE 6P CN,0,0.0,16.48,2.0,WK1,2018
4,912500335,106,2018 PD 02 WK 2,ANDRS VLY HOLY GOSE 6P CN,0,0.0,18.72,3.0,WK2,2018

In [42]:
# Checking for negative values in the scanned_retail_dollars column


# We remove this data where it does not affect out_of_stock values --- rationale : these are returns that have not impacted out-of-stock shelves;  we will regard 'returns' as abnormal
# behaviour but to be tolerated.  A negative profit (as indicated by the gross_margin_dollars var.) may be indicative of other factors -- discounts, sales, special events , etc

a = new_merge_dat['scanned_retail_dollars'] < 0
b = new_merge_dat['target_out_stock'] > 0

sum(a&b)

1

In [43]:
# So in this case sum(a&b) equals 1 , that is  1 row is deleted.
u = [not(x) for x in a & b]
new_merge_dat = new_merge_dat[u]

In [44]:
''' We initially dropped the following variables :
  'scanned_lbs'
  'division_code'; has a single value, namely 705


  The variables below are constructed in order to be used later in an optimization formulation
  Derived variables (features)
  1) profit_unit = 'gross_margin_dollars' / 'scanned_movement'

  2) retail_price_unit = 'scanned_retail_dollars' / 'scanned_movement'


'''



new_merge_dat = new_merge_dat.assign(profit_unit = new_merge_dat.gross_margin_dollars/new_merge_dat.scanned_movement)

new_merge_dat = new_merge_dat.assign(retail_price_unit  = new_merge_dat.scanned_retail_dollars/new_merge_dat.scanned_movement)

In [45]:
'''
    Removing the upc_description' , 'storenum' combination for which there is no indication of out of stock over the modelling period;
    that is products in these stores were never out of stock over the modelling period.

'''
def transform(dat):
    # Creation of features (derived variables) from the initial modelling dataset
    dat['scanned_retail_dollars:scanned_movement'] = dat['scanned_retail_dollars']*dat['scanned_movement']

    # binomial target: (0, 1) vector
    dat['logistic_target'] = [1 if x >= 1 else 0 for x in dat['target_out_stock']]



    '''
    Removing 'upc_description' , 'storenum' combination for which there is no indication of out of stock over the modelling period; that is products in these stores
    were never out of stock over the modelling period.

    '''
    out_stock_cnts = dat.groupby(['upc_description', 'storenum'])['target_out_stock'].sum('target_out_stock')
    out_stock_cnts = out_stock_cnts.reset_index()
    y = out_stock_cnts['target_out_stock'] >= 1
    dat = dat.merge(out_stock_cnts[['upc_description', 'storenum']][y], on = ['upc_description', 'storenum'], how = 'inner', suffixes = ("_x", None))
    return(dat)

In [46]:
# Applying the transform function

new_merge2 = transform(dat = new_merge_dat)
new_merge2.shape

(546101, 14)

In [47]:
new_merge2.head()

,upc,storenum,new_year_mth_wk,upc_description,target_out_stock,gross_margin_dollars,scanned_retail_dollars,scanned_movement,wks,year,profit_unit,retail_price_unit,scanned_retail_dollars:scanned_movement,logistic_target
0,1612102200,822,2018 PD 01 WK 1,JK SCRUMPY ORG HRD CD BTL,0,0.0,8.99,1.0,WK1,2018,0.0,8.99,8.99,0
1,1612102200,822,2018 PD 01 WK 2,JK SCRUMPY ORG HRD CD BTL,0,0.0,6.99,1.0,WK2,2018,0.0,6.99,6.99,0
2,1612102200,822,2018 PD 01 WK 3,JK SCRUMPY ORG HRD CD BTL,0,0.0,6.99,1.0,WK3,2018,0.0,6.99,6.99,0
3,1612102200,822,2018 PD 01 WK 4,JK SCRUMPY ORG HRD CD BTL,0,0.0,13.98,2.0,WK4,2018,0.0,6.99,27.96,0
4,1612102200,822,2018 PD 02 WK 1,JK SCRUMPY ORG HRD CD BTL,0,0.0,6.99,1.0,WK1,2018,0.0,6.99,6.99,0

In [48]:
# saving the dataset 'new_merge2' as shelves_relevant.csv to the My Google Drive
new_merge2.to_csv('/content/gdrive/My Drive/Beer/shelves_relevant.csv', index = False)

In [49]:
import pandas as pd
shelves_relevant= pd.read_csv('/content/gdrive/MyDrive/Beer/shelves_relevant.csv')
shelves_relevant.tail()

,upc,storenum,new_year_mth_wk,upc_description,target_out_stock,gross_margin_dollars,scanned_retail_dollars,scanned_movement,wks,year,profit_unit,retail_price_unit,scanned_retail_dollars:scanned_movement,logistic_target
546096,89944300105,879,2020 PD 06 WK 4,DMND KNOT INDUSTL IPA BTL,0,0.0,13.98,2.0,WK4,2020,0.0,6.990,27.96,0
546097,89944300105,879,2020 PD 07 WK 1,DMND KNOT INDUSTL IPA BTL,0,0.0,20.97,3.0,WK1,2020,0.0,6.990,62.91,0
546098,89944300105,879,2020 PD 07 WK 2,DMND KNOT INDUSTL IPA BTL,0,0.0,34.95,5.0,WK2,2020,0.0,6.990,174.75,0
546099,89944300105,879,2020 PD 07 WK 3,DMND KNOT INDUSTL IPA BTL,0,0.0,27.26,4.0,WK3,2020,0.0,6.815,109.04,0
546100,89944300105,879,2020 PD 08 WK 1,DMND KNOT INDUSTL IPA BTL,0,0.0,13.98,2.0,WK1,2020,0.0,6.990,27.96,0